media:
  # All uploaded media goes inside static/uploads
  input: static/uploads
  output: /uploads

content:
  # Blog posts in /blog
  - name: blog
    label: Blog posts
    type: collection
    path: blog
    format: yaml-frontmatter
    filename: "{year}-{month}-{day}-{primary}.md"
    fields:
      - { name: title,        label: Title,        type: string, required: true }
      - { name: description,  label: Description,  type: text }
      - { name: authors,      label: Authors,      type: string, list: true }
      - { name: tags,         label: Tags,         type: string, list: true }
      - { name: image,        label: Cover image,  type: image }
      - { name: draft,        label: Draft,        type: boolean }
      - { name: body,         label: Body,         type: rich-text }

  # Docs in /docs (tree view, supports nested folders)
  - name: docs
    label: Docs
    type: collection
    path: docs
    format: yaml-frontmatter
    subfolders: true
    view:
      layout: tree
      node:
        filename: index.md
    fields:
      - { name: title,        label: Title,        type: string, required: true }
      - { name: sidebar_label,label: Sidebar label,type: string }
      - { name: slug,         label: Slug,         type: string }
      - { name: body,         label: Body,         type: rich-text }
